stages:
- name: push to remote
  steps:
  - publishCatalogConfig:
      path: ./alpine/
      catalogTemplate: $CHART_APP_NAME
      version: $CHART_APP_VERSION
      gitUrl: https://github.com/bmdepesa/test-charts.git
      gitBranch: master
      gitAuthor: brandon
      gitEmail: brandon@gmail.com
    env:
      CHART_APP_NAME: test-chart
      CHART_APP_VERSION: v1
      CICD_SUBSTITUTE_VARS: CHART_APP_NAME,CHART_APP_VERSION
    envFrom:
    - sourceName: test-secret
      sourceKey: USERNAME
      targetKey: USERNAME
    - sourceName: test-secret
      sourceKey: PASSWORD
      targetKey: PASSWORD
timeout: 60
notification: {}
