stages:
- name: push to remote
  steps:
  - publishCatalogConfig:
      path: ./alpine/
      catalogTemplate: alpine-test-brandon
      version: ${CHART_VERSION}
      gitUrl: https://github.com/bmdepesa/test-charts.git
      gitBranch: master
      gitAuthor: brandon
      gitEmail: brandon@gmail.com
    env:
      CHART_DESCRIPTION: test description from file
      CHART_VERSION: v3
    envFrom:
    - sourceName: git
      sourceKey: USERNAME
      targetKey: USERNAME
    - sourceName: git
      sourceKey: PASSWORD
      targetKey: PASSWORD
timeout: 60
notification: {}
